- name: 创建相关目录
  file:
    path: "{{ item }}"
    state: directory
    directory_mode: 755
  with_items:
    - "{{ Manifests_path }}"
    - "{{ haproxy_path }}"
    - '/etc/systemd/system/kubelet.service.d'
    - "{{ kubelete_data_path }}"
    - "{{ kubernetes_log }}"
    - "{{ etcd_data_path }}"
    - '~/.kube/'

- name: 分发资源文件模板到每台Master
  template: src={{ item.src }} dest={{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}
  with_items:
    - { src: 'kube-apiserver.yml.j2', dest: "{{ Manifests_path }}" }
    - { src: 'kube-controller-manager.yml.j2', dest: "{{ Manifests_path }}" }
    - { src: 'kube-scheduler.yml.j2', dest: "{{ Manifests_path }}" }
    - { src: 'haproxy.yml.j2', dest: "{{ Manifests_path }}" }
    - { src: 'keepalived.yml.j2', dest: "{{ Manifests_path }}" }
    - { src: 'etcd.yml.j2', dest: "{{ Manifests_path }}" }
    - { src: 'etcd.config.yml.j2', dest: "{{ etcd_path }}" }
    - { src: 'encryption.yml.j2', dest: "{{ kubernetes_path }}" }
    - { src: 'audit-policy.yml.j2', dest: "{{ kubernetes_path }}" }
    - { src: 'haproxy.cfg.j2', dest: "{{ haproxy_path }}" }
    - { src: 'kubelet.service.j2', dest: '/lib/systemd/system' }
    - { src: '10-kubelet.conf.j2', dest: '/etc/systemd/system/kubelet.service.d' }

- name: 启动kubelet
  shell: systemctl enable kubelet.service && systemctl start kubelet.service

- name: 设置admin kubeconfig
  shell: /usr/bin/cp {{ kubernetes_path }}/admin.conf ~/.kube/config
